export const DEFAULT_QZONE_SETTINGS = {
  credentialPath: 'data/qzone/credentials.json',
  qrLoginTimeoutSeconds: 120,
  qrPollIntervalMs: 2000,
  cookieTtlSeconds: 600,
  timeoutMs: 10_000,
  defaultFeedCount: 5,
  maxImageBytes: 8 * 1024 * 1024,
  maxImages: 9,
  imageCachePath: 'data/qzone/temp/image',
  modelImageCachePath: 'data/qzone/temp/model',
  videoCachePath: 'data/qzone/temp/video',
  imageCacheTtlSeconds: 7 * 24 * 60 * 60,
  imageCacheCleanupIntervalSeconds: 24 * 60 * 60,
  maxModelImages: 9,
  maxModelImageBytes: 4 * 1024 * 1024,
  maxModelImageTotalBytes: 16 * 1024 * 1024,
  maxVideoBytes: 32 * 1024 * 1024,
  maxVideos: 3,
  allowedImageHosts: [
    '*.qpic.cn',
    '*.qlogo.cn',
    '*.qq.com',
    '*.gtimg.cn',
  ],
} as const
